# Golang CircleCI 2.0 configuration file
#
workflows:
  version: 2
  main:
    jobs:
      - go-current
      - go-previous
      - go-latest
base: &base
  working_directory: /go/src/github.com/sklemmer/go-autoupdate
  steps:
    - checkout
    - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
    - run: dep ensure -v
    - run: go vet ./...
    - run: go test -v ./...
    - run: go test -coverprofile=c.out ./...
    #- store_artifacts:
    #    path: coverage/
version: 2
jobs:
  current:
    docker:
      - image: circleci/golang:1.10.0
    <<: *base
  previous:
    docker:
      - image: circleci/golang:1.9.4
    <<: *base
  latest:
    docker:
      - image: circleci/golang:latest
    <<: *base