# Golang CircleCI 2.0 configuration file
#
workflows:
  version: 2
  main:
    jobs:
      - current
      - previous
      - latest
      - junit-report:
          requires:
            - current
            - previous
            - latest
      - docs:
          requires:
            - junit-report
          filters:
            branches:
              only: master
base: &base
  working_directory: /go/src/github.com/sklemmer/go-autoupdate
  steps:
    - checkout
    - run:
        command: |
          curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
          dep ensure -v
    - run: go vet ./...
    - run: go test -v ./...
    - run:
        command: |
          echo 'mode: atomic' > coverage.txt
          go list ./... | xargs -n1 -I{} sh -c 'go test -covermode=atomic -coverprofile=coverage.tmp {} && tail -n +2 coverage.tmp >> coverage.txt'
          rm coverage.tmp
version: 2
jobs:
  current:
    docker:
      - image: circleci/golang:1.10
    <<: *base
  previous:
    docker:
      - image: circleci/golang:1.9
    <<: *base
  latest:
    docker:
      - image: circleci/golang:latest
    <<: *base
  junit-report:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/sklemmer/go-autoupdate
    steps:
      - checkout
      - run:
          command: |
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure -v
      - run:
          command: |
            mkdir -p ~/reports
            go get -u github.com/jstemmer/go-junit-report
            go test -v ./... 2>&1 | go-junit-report > ~/reports/junit.xml
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports
  docs:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/sklemmer/go-autoupdate
    steps:
      - checkout
      - run: go get github.com/davecheney/godoc2md
      - run:
          command: |
            mkdir -p /go/src/github.com/sklemmer/go-autoupdate/docs
            godoc2md github.com/sklemmer/go-autoupdate > /go/src/github.com/sklemmer/go-autoupdate/docs/README.md
      - store_artifacts:
          path: docs/